base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.sighup ,name='sighup'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('', include('base.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
        
class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    descriotion = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class Signupform(UserCreationForm):
    class meta:
        model = User
        fields = ('username', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

base/views.py
from django.shortcuts import render ,redirect
from django.http import HttpResponse
from item.models import Category, Item
from .forms import Signupform
# Create your views here.

def home(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'home.html', {
        'categories': categories,
        'items': items,
    })


def contact(request):
    return render(request, 'contact.html')

def sighup(request):
    if request.method == 'POST':
        form = Signupform(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:        
        form = Signupform


    return render(request, 'signup.html',{
        'form': form
    })

item/views.py
from django.shortcuts import render , get_object_or_404
from .models import Item
# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'detail.html' , {
        'item' : item ,
        'related_items' :related_items
    })

templates/contact.html
{%  extends 'index.html' %}

{% block title %}contact{% endblock %}

{% block content %}
<div>
    <h1>welcome to contact</h1>
</div>
{% endblock %}

templates/detail.html
{%  extends 'index.html' %}

{% block title %}{{ item.name }}{% endblock %}


{% block content %}
<div class="grid grid-cols-5 gap-6 bg-gray-100">
    <div class="col-span-3 ">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl ">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-700">price: {{ item.price }}</p>
        <p class="text-gray-700">seller : {{ item.created_by.username }}</p>
        {% if item.descriotion %}
        <p class="text-gray-700">description :<br>{{ item.descriotion }}</p>
        {% endif %}
        <a href="#" class="inline-block mt-6 px-6 py-6 text-lg  text-lg bg-teal-500 text-white rounded-xl hover:bg-teal-700">contact seller</a>
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-center text-2xl"> related items </h2>
    <div class="grid grid-cols-3 gap-3">
       {% for item in related_items %}
       <div>
          <a href="{% url 'item:detail' item.id %}">
             <div>
                <img src="{{ item.image.url }}" class="rounded-t-xl h-64  ">
             </div>
             <div class="p-6 bg-white  rounded-b-xl">
                <h2 class="text-2xl">{{ item.name }}</h2>
                <p class="text-gray-500">price: {{ item.price }}</p>
             </div>
          </a>
       </div>
       {% endfor %}
    </div>
 </div>
 
{% endblock %}

templates/home.html
{%  extends 'index.html' %}

{% block title %}home{% endblock %}

{% block content %}
   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
      <h2 class="mb-12 text-center text-2xl"> newest items </h2>
      <div class="grid grid-cols-3 gap-3">
         {% for item in items %}
         <div>
            <a href="{% url 'item:detail' item.id %}">
               <div>
                  <img src="{{ item.image.url }}" class="rounded-t-xl h-64  ">
               </div>
               <div class="p-6 bg-white  rounded-b-xl">
                  <h2 class="text-2xl">{{ item.name }}</h2>
                  <p class="text-gray-500">price: {{ item.price }}</p>
               </div>
            </a>
         </div>
         {% endfor %}
      </div>
   </div>
   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
      <h2 class="mb-12 text-center text-2xl"> categories </h2>
      <div class="grid grid-cols-3 gap-3">
         {% for category in categories %}
         <div>
            <a href="#">
               <div class="p-6 bg-white  rounded-b-xl">
                  <h2 class="text-2xl">{{ category.name }}</h2>
                  <p class="text-gray-500">{{ category.items.count }} items</p>
               </div>
            </a>
         </div>
         {% endfor %}
      </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta  name="homepage" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
       <title>market \ {% block title %}{% endblock %} </title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/"><b>home page</b></a>
            <div class="space-x-6">
                <a>item</a>
                <a href="#">browse</a>
                <a href="signup/" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">sign up</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">login</a>
            </div>
        </nav>
        
        <div class="px-6 py-6">
            {% block content %}

            {% endblock %}
        </div>


        <footer class="px-6 py-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">about</h3>

                <p class="text-lg text-gray-500">blalallslsalslalslasalslasaghaghgagdggduwgud</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">menu</h3>

                <ul class="space-y-2">
                     <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">about</a></li>
                     <li><a href="{% url 'contact'%}" class="text-lg text-teal-500 hover:text-teal-700">contact</a></li>
                     <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">privacy police</a></li>
                     <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">terms of use</a></li>
                </ul>
            </div>
        </footer>
    </body>

</html>

templates/signup.html
{%  extends 'index.html' %}

{% block title %}sign up {% endblock %}
{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Signup</h1>
    <form method="post" action=".">
        {% csrf_token %}

        
        <div class="mb-3">
            <label class="inline-block mb-2">username</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">password</label>
            {{ form.password1  }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2"> repeat password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or from.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors  }}
        </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>

    </form>
</div>
{% endblock %}